
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MUHAMMAD KASHIF
 */
public class PRODUCT extends javax.swing.JFrame {

    /**
     * Creates new form DEFINE_ROLE
     */
    ConnectOracle con_obj = new ConnectOracle();
    Connection con=con_obj.EstablishCon();
    Statement stmt = null;
    PreparedStatement pstmt = null;
    ResultSet res;
    DefaultTableModel d;
    public PRODUCT() {
        try {
            initComponents();
            this.setLocationRelativeTo(null);
            
            String name,query="select CATEGORY_NAME FROM CATEGORY ORDER BY CATEGORY_ID";
            pstmt = con.prepareStatement(query);
            res = pstmt.executeQuery();
            while (res.next()) {
                name=res.getString(1);
                combo.addItem(name);
            }
            prod();
            query="select NAME FROM SUPPLIER ORDER BY SUPPLIER_ID ";
            pstmt = con.prepareStatement(query);
            res = pstmt.executeQuery();
            while (res.next()) {
                name=res.getString(1);
                sup.addItem(name);
            }
        } catch (SQLException ex) {
            Logger.getLogger(PRODUCT.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    
  public boolean confirminsert()
    {
        String b=B.getText();
        String c=C.getText();
        String d=D.getText();
        String e=E.getText();
        String f=F.getText();
        
        if( b.length()>0 && c.length()>0&& d.length()>0&& e.length()>0&& f.length()>0)
            return true;
        else
            return false;
    }
    public boolean confirm()
    {
        String a=A.getText();
        String b=B.getText();
        String c=C.getText();
        String d=D.getText();
        String e=E.getText();
        String f=F.getText();
        
        if( a.length()>0 &&b.length()>0 && c.length()>0&& d.length()>0&& e.length()>0&& f.length()>0)
            return true;
        else
            return false;
    }
    public void prod(){
             int c;
        try {
            String query="select * from product order by product_id";
            pstmt = con.prepareStatement(query);
            res = pstmt.executeQuery();
            ResultSetMetaData rsd = res.getMetaData();
            c = rsd.getColumnCount();
            d = (DefaultTableModel) PRODUCTTABLE.getModel();
            d.setRowCount(0);
            while (res.next()) {
                Vector v2 = new Vector();
                for (int i = 1; i <= c; i++) {
                    v2.add(res.getString("product_id"));
                    v2.add(res.getString("product_name"));
                    v2.add(res.getString("PRODUCT_PRICE"));
                    v2.add(res.getString("PRODUCT_QUANTITY"));
                    v2.add(res.getString("CATEGORY_ID"));
                    v2.add(res.getString("PRODUCT_DESCRIPTION"));
                    v2.add(res.getString("SUPPLIER_ID"));

                }
                d.addRow(v2);

            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        E = new javax.swing.JTextField();
        B = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        A = new javax.swing.JTextField();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        label3 = new java.awt.Label();
        jButton3 = new javax.swing.JButton();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        C = new javax.swing.JTextField();
        D = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        PRODUCTTABLE = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        label8 = new java.awt.Label();
        combo = new javax.swing.JComboBox<>();
        F = new javax.swing.JTextField();
        G = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sup = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        E.setText("MAXIMUM 40 CHARACTER");
        E.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EMouseClicked(evt);
            }
        });
        E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EActionPerformed(evt);
            }
        });
        getContentPane().add(E, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 160, 30));

        B.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BKeyTyped(evt);
            }
        });
        getContentPane().add(B, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 140, 30));

        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/back.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        A.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AKeyTyped(evt);
            }
        });
        getContentPane().add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 60, 30));

        label4.setBackground(new java.awt.Color(0, 0, 0));
        label4.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("PRODUCT ID : ");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 120, -1));

        label5.setBackground(new java.awt.Color(0, 0, 0));
        label5.setFont(new java.awt.Font("Engravers MT", 1, 10)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setText("DESCRIPTION : ");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 120, -1));

        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, -1));

        jButton2.setText("INSERT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        label3.setBackground(new java.awt.Color(0, 0, 0));
        label3.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("CATEGORY : ");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, -1));

        label6.setBackground(new java.awt.Color(0, 0, 0));
        label6.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        label6.setForeground(new java.awt.Color(255, 255, 255));
        label6.setText("PRODUCT NAME : ");
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 150, -1));

        label7.setBackground(new java.awt.Color(0, 0, 0));
        label7.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        label7.setForeground(new java.awt.Color(255, 255, 255));
        label7.setText("PRODUCT PRICE : ");
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 160, -1));

        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });
        C.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CKeyTyped(evt);
            }
        });
        getContentPane().add(C, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 90, 30));

        D.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DKeyTyped(evt);
            }
        });
        getContentPane().add(D, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 70, 30));

        PRODUCTTABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "PRICE", "QUANTITY", "CATEGORY", "DESCRIPTION", "SUPPLIER ID"
            }
        ));
        PRODUCTTABLE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PRODUCTTABLEMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PRODUCTTABLE);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 330, 360));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/OFF WHITE.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 350, 430));

        label8.setBackground(new java.awt.Color(0, 0, 0));
        label8.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        label8.setForeground(new java.awt.Color(255, 255, 255));
        label8.setText("QUANTITY : ");
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 110, -1));

        combo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboMouseClicked(evt);
            }
        });
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        getContentPane().add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 120, -1));

        F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FActionPerformed(evt);
            }
        });
        F.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FKeyTyped(evt);
            }
        });
        getContentPane().add(F, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 30, -1));

        G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GActionPerformed(evt);
            }
        });
        getContentPane().add(G, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 100, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SUPPLIER :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        getContentPane().add(sup, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 120, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/BLACK.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Admin_Dashboard ad = new Admin_Dashboard();
        ad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        A.setText("");
        B.setText("");
        C.setText("");
        D.setText("");
        E.setText("");
        F.setText("");
        G.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(confirm())
        {
            String a=A.getText();
            int id=Integer.parseInt(a);  
            try {
                String query="delete from PRODUCT where PRODUCT_ID="+id;
                pstmt = con.prepareStatement(query);
            res = pstmt.executeQuery();
        JOptionPane.showMessageDialog(null, "Record Deleted!!!");
            prod();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Can'nt able to delete Record!!!");
                Admin_Dashboard ad=new Admin_Dashboard();
                ad.setVisible(true);
                dispose();
            }
        }
        else
        {
        JOptionPane.showMessageDialog(null, "Insert Require Information!!!");
        }
        A.setText("");
        B.setText("");
        C.setText("");
        D.setText("");
        E.setText("");
        F.setText("");
        G.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            String a=A.getText();
            int p_id=Integer.parseInt(a);
        if(confirm())
        {
        String b=B.getText();
        String c=C.getText(); 
        int cc=Integer.parseInt(c);
        String d=D.getText();
        int dd=Integer.parseInt(d);
        String e=E.getText();  
        String f=F.getText();  
        int ff=Integer.parseInt(f);
         int num=sup.getSelectedIndex();
        try {
                String query = "UPDATE PRODUCT SET SUPPLIER_ID="+(num+1)+",PRODUCT_NAME='"+b+"', PRODUCT_DESCRIPTION='"+e+"', PRODUCT_PRICE="+cc+",PRODUCT_QUANTITY="+dd+", CATEGORY_ID="+ff+" WHERE PRODUCT_ID="+p_id;
                pstmt = con.prepareStatement(query);
            res = pstmt.executeQuery();
        JOptionPane.showMessageDialog(null, "Record Updated!!!");
            prod();
            } catch (SQLException ex) {
                Logger.getLogger(DEFINE_ROLE.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
        JOptionPane.showMessageDialog(null, "Insert Require Information!!!");
        }
        A.setText("");
        B.setText("");
        C.setText("");
        D.setText("");
        E.setText("");
        F.setText("");
        G.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(confirminsert())
        {
        String b=B.getText();
        String c=C.getText();
        String d=D.getText();
        String e=E.getText();
        String f=F.getText();  
        int ci=Integer.parseInt(f);  
      int id=0;
        try {
                String query="select count(PRODUCT_ID) FROM PRODUCT";
                pstmt = con.prepareStatement(query);
            res = pstmt.executeQuery();
                    while (res.next()) {
                id=Integer.parseInt(res.getString(1));
            }
            } catch (SQLException ex) {
            try {
                String query="select max(PRODUCT_ID) FROM PRODUCT";
                pstmt = con.prepareStatement(query);
                res = pstmt.executeQuery();
                while (res.next()) {
                    id=Integer.parseInt(res.getString(1));
                }
            } catch (SQLException ex1) {
                Logger.getLogger(PRODUCT.class.getName()).log(Level.SEVERE, null, ex1);
            }
            }
        
    int num=sup.getSelectedIndex();
            try {
                String query="insert into PRODUCT VALUES("+(id+1)+",'"+b+"','"+e+"',"+c+","+d+","+ci+","+(num+1)+")";
                pstmt = con.prepareStatement(query);
            res = pstmt.executeQuery();
            prod();
            } catch (SQLException ex) {
                Logger.getLogger(DEFINE_ROLE.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
        JOptionPane.showMessageDialog(null, "Insert Require Information!!!");
        }
        A.setText("");
        B.setText("");
        C.setText("");
        D.setText("");
        E.setText("");
        F.setText("");
        G.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void PRODUCTTABLEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PRODUCTTABLEMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tmodel=(DefaultTableModel)PRODUCTTABLE.getModel();
        int selectrowindex=PRODUCTTABLE.getSelectedRow();
        A.setText(tmodel.getValueAt(selectrowindex,0).toString());
        B.setText(tmodel.getValueAt(selectrowindex,1).toString());
        C.setText(tmodel.getValueAt(selectrowindex,2).toString());
        D.setText(tmodel.getValueAt(selectrowindex,3).toString());
        F.setText(tmodel.getValueAt(selectrowindex,4).toString());
        E.setText(tmodel.getValueAt(selectrowindex,5).toString());
        
    }//GEN-LAST:event_PRODUCTTABLEMouseClicked

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
        String option=(String) combo.getSelectedItem().toString();
    G.setText(option);
    int num=combo.getSelectedIndex();
    num++;
    F.setText(String.valueOf(num));
    }//GEN-LAST:event_comboActionPerformed

    private void FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FActionPerformed

    private void comboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMouseClicked

    private void GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GActionPerformed

    private void AKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c))
        {
            evt.consume();
        }
    }//GEN-LAST:event_AKeyTyped

    private void CKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c))
        {
            evt.consume();
        }
    }//GEN-LAST:event_CKeyTyped

    private void DKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c))
        {
            evt.consume();
        }
    }//GEN-LAST:event_DKeyTyped

    private void FKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_FKeyTyped

    private void EMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EMouseClicked
        // TODO add your handling code here:
        E.setText("");
    }//GEN-LAST:event_EMouseClicked

    private void BKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
            B.setEditable(true);
        }
        else
        {
            B.setEditable(false);
        }
    }//GEN-LAST:event_BKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DEFINE_ROLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DEFINE_ROLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DEFINE_ROLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DEFINE_ROLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DEFINE_ROLE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A;
    private javax.swing.JTextField B;
    private javax.swing.JTextField C;
    private javax.swing.JTextField D;
    private javax.swing.JTextField E;
    private javax.swing.JTextField F;
    private javax.swing.JTextField G;
    private javax.swing.JTable PRODUCTTABLE;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private javax.swing.JComboBox<String> sup;
    // End of variables declaration//GEN-END:variables
}
