
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MUHAMMAD KASHIF
 */
public class SUPPLIER extends javax.swing.JFrame {
 ConnectOracle con_obj = new ConnectOracle();
    Connection con=con_obj.EstablishCon();
    PreparedStatement pstmt = null;
    ResultSet res;
     DefaultTableModel d;
    /**
     * Creates new form DEFINE_ROLE
     */
    public SUPPLIER() {
        initComponents();
    this.setLocationRelativeTo(null);
    supply();
    }
public void supply(){
             int c;
        try {
            
            String query="select * from SUPPLIER order by SUPPLIER_ID";
            pstmt = con.prepareStatement(query);
            res = pstmt.executeQuery();
            ResultSetMetaData rsd = res.getMetaData();
            c = rsd.getColumnCount();
            d = (DefaultTableModel) supplytable.getModel();
            d.setRowCount(0);
            while (res.next()) {
                Vector v2 = new Vector();
                for (int i = 1; i <= c; i++) {
                    v2.add(res.getString("SUPPLIER_ID"));
                    v2.add(res.getString("NAME"));
                    v2.add(res.getString("ADDRESS"));
                    v2.add(res.getString("PHONE"));
                    v2.add(res.getString("EMAIL"));
                    v2.add(res.getString("DESCRIPTION"));

                }
                d.addRow(v2);

            }

        } catch (SQLException ex) {
            ex.printStackTrace();
          //  Logger.getLogger(Rooms.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        A = new javax.swing.JTextField();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        F = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        C = new javax.swing.JTextField();
        D = new javax.swing.JTextField();
        E = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        supplytable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        B.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BKeyTyped(evt);
            }
        });
        getContentPane().add(B, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 140, 30));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/back.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 30));

        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        A.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AKeyTyped(evt);
            }
        });
        getContentPane().add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 70, 30));

        label3.setBackground(new java.awt.Color(0, 0, 0));
        label3.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("ADDRESS : ");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 90, -1));

        label4.setBackground(new java.awt.Color(0, 0, 0));
        label4.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("SUPPLIER ID : ");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 120, -1));

        label5.setBackground(new java.awt.Color(0, 0, 0));
        label5.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setText("DESCRIPTION : ");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 130, -1));

        F.setText("MAXIMUM 40 CHARACTER");
        F.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FMouseClicked(evt);
            }
        });
        F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FActionPerformed(evt);
            }
        });
        getContentPane().add(F, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 170, 40));

        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        jButton2.setText("INSERT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));

        label6.setBackground(new java.awt.Color(0, 0, 0));
        label6.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        label6.setForeground(new java.awt.Color(255, 255, 255));
        label6.setText("EMAIL : ");
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 70, -1));

        label7.setBackground(new java.awt.Color(0, 0, 0));
        label7.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        label7.setForeground(new java.awt.Color(255, 255, 255));
        label7.setText("SUPPLIER NAME : ");
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 160, -1));

        label8.setBackground(new java.awt.Color(0, 0, 0));
        label8.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        label8.setForeground(new java.awt.Color(255, 255, 255));
        label8.setText("PHONE : ");
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 70, -1));

        C.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CKeyTyped(evt);
            }
        });
        getContentPane().add(C, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 140, 30));

        D.setText("@gmail.com");
        getContentPane().add(D, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 140, 30));

        E.setText("MAXIMUM 40 CHARACTER");
        E.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EMouseClicked(evt);
            }
        });
        E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EActionPerformed(evt);
            }
        });
        getContentPane().add(E, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 170, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/BLACK.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 440));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));
        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        supplytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "ADDRESS", "PHONE", "EMAIL", "DESCRIPTION"
            }
        ));
        supplytable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplytableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(supplytable);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 340, 380));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/OFF WHITE.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 350, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EActionPerformed
public boolean confirminsert()
    {
        String b=B.getText();
        String c=C.getText();
        String d=D.getText();
        String e=E.getText();
        String f=F.getText();
        
        if( b.length()>0 && c.length()>0&& d.length()>0&& e.length()>0&& f.length()>0)
            return true;
        else
            return false;
    }
public boolean confirm()
    {
        String a=A.getText();
        String b=B.getText();
        String c=C.getText();
        String d=D.getText();
        String e=E.getText();
        String f=F.getText();
        
        if( a.length()>0 && b.length()>0 && c.length()>0&& d.length()>0&& e.length()>0&& f.length()>0)
            return true;
        else
            return false;
    }
    private void supplytableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplytableMouseClicked
        // TODO add your handling code here:
          DefaultTableModel tmodel=(DefaultTableModel)supplytable.getModel();
        int selectrowindex=supplytable.getSelectedRow();
        A.setText(tmodel.getValueAt(selectrowindex,0).toString());
        B.setText(tmodel.getValueAt(selectrowindex,1).toString());
        E.setText(tmodel.getValueAt(selectrowindex,2).toString());
        C.setText(tmodel.getValueAt(selectrowindex,3).toString());
        D.setText(tmodel.getValueAt(selectrowindex,4).toString());
        F.setText(tmodel.getValueAt(selectrowindex,5).toString());
    }//GEN-LAST:event_supplytableMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Admin_Dashboard ad = new Admin_Dashboard();
        ad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        A.setText("");
        B.setText("");
        C.setText("");
        D.setText("");
        E.setText("");
        F.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(confirminsert())
        {
        String b=B.getText();
        String c=C.getText();  
        String d=D.getText();
        String e=E.getText(); 
        String f=F.getText();
      int id=0;
        try {
                String query="select count(SUPPLIER_ID) FROM SUPPLIER";
                pstmt = con.prepareStatement(query);
            res = pstmt.executeQuery();
                    while (res.next()) {
                id=Integer.parseInt(res.getString(1));
            }
            } catch (SQLException ex) {
            try {
                String query="select max(SUPPLIER_ID) FROM SUPPLIER";
                pstmt = con.prepareStatement(query);
                res = pstmt.executeQuery();
            } catch (SQLException ex1) {
                Logger.getLogger(SUPPLIER.class.getName()).log(Level.SEVERE, null, ex1);
            }
            }
            try {
                String query="insert into SUPPLIER VALUES("+(id+1)+",'"+b+"','"+e+"','"+c+"','"+d+"','"+f+"')";
                pstmt = con.prepareStatement(query);
            res = pstmt.executeQuery();
        JOptionPane.showMessageDialog(null, "SUPPLIER ADDED!!!");
            supply();
            } catch (SQLException ex) {
                Logger.getLogger(DEFINE_ROLE.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
        JOptionPane.showMessageDialog(null, "Insert Require Information!!!");
        }
           A.setText("");
B.setText("");
C.setText("");
D.setText("");
E.setText("");
F.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(confirm())
        {
            String a=A.getText();
            int id=Integer.parseInt(a);
        String b=B.getText();
        String c=C.getText();
        String d=D.getText();
        String e=E.getText();  
        String f=F.getText();  
            try {
                String query="update SUPPLIER  set NAME='"+b+"',ADDRESS='"+e+"',PHONE="+c+",EMAIL='"+d+"', DESCRIPTION='"+f+"' where SUPPLIER_ID="+id;
                pstmt = con.prepareStatement(query);
            res = pstmt.executeQuery();
        JOptionPane.showMessageDialog(null, "Record Updated!!!");
            supply();
            } catch (SQLException ex) {
                Logger.getLogger(DEFINE_ROLE.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
        JOptionPane.showMessageDialog(null, "Insert Require Information!!!");
        }
        A.setText("");
B.setText("");
C.setText("");
D.setText("");
E.setText("");
F.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(confirm())
        {
            String a=A.getText();
            int id=Integer.parseInt(a);  
            try {
                String query="delete from SUPPLIER where SUPPLIER_ID="+id;
                pstmt = con.prepareStatement(query);
            res = pstmt.executeQuery();
        JOptionPane.showMessageDialog(null, "Record Deleted!!!");
            supply();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Can'nt able to delete Record!!!");
                Admin_Dashboard ad=new Admin_Dashboard();
                ad.setVisible(true);
                dispose();
            }
        }
        else
        {
        JOptionPane.showMessageDialog(null, "Insert Require Information!!!");
        }
         A.setText("");
B.setText("");
C.setText("");
D.setText("");
E.setText("");
F.setText("");

    }//GEN-LAST:event_jButton4ActionPerformed

    private void AKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c))
        {
            evt.consume();
        }
    }//GEN-LAST:event_AKeyTyped

    private void CKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c))
        {
            evt.consume();
        }
    }//GEN-LAST:event_CKeyTyped

    private void BKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
            B.setEditable(true);
        }
        else
        {
            B.setEditable(false);
        }
    }//GEN-LAST:event_BKeyTyped

    private void FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FActionPerformed

    private void EMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EMouseClicked
        // TODO add your handling code here:
        E.setText("");
    }//GEN-LAST:event_EMouseClicked

    private void FMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FMouseClicked
        // TODO add your handling code here:
        F.setText("");
    }//GEN-LAST:event_FMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DEFINE_ROLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DEFINE_ROLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DEFINE_ROLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DEFINE_ROLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DEFINE_ROLE().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A;
    private javax.swing.JTextField B;
    private javax.swing.JTextField C;
    private javax.swing.JTextField D;
    private javax.swing.JTextField E;
    private javax.swing.JTextField F;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private javax.swing.JTable supplytable;
    // End of variables declaration//GEN-END:variables
}
